// apps/frontend/src/features/room-join/RoomJoinModal.svelte
<script lang="ts">
  import { api } from '@/shared/api/endpoints';
  import { roomStore } from '@/entities/room/store';
  import { playerStore } from '@/entities/player/store';
  import type { RoomInfo } from '@shared/types/room';
  import { FORMAT_LABELS } from '@shared/constants/index';
  import s from './RoomJoinModal.module.scss';

  export let room: RoomInfo | null;
  export let isOpen: boolean;
  export let onClose: () => void;
  export let onSuccess: () => void;

  let formData = { nickname: '', password: '' };
  let isLoading = false;
  let error = '';

  const handleSubmit = async (e: Event) => {
    e.preventDefault();
    if (!room) return;

    error = '';

    if (!formData.nickname.trim()) {
      error = '닉네임을 입력해주세요';
      return;
    }

    if (room.locked && !formData.password) {
      error = '비밀번호를 입력해주세요';
      return;
    }

    isLoading = true;
    try {
      const response = await api.joinRoom({
        roomId: room.id,
        nickname: formData.nickname,
        password: formData.password || undefined,
      });

      roomStore.setRoom({
        id: room.id,
        title: room.title,
        locked: room.locked,
        format: room.format,
        overtime: room.overtime,
        playerCount: room.playerCount,
      });

      playerStore.setMe({
        id: response.playerId,
        nickname: formData.nickname,
        ready: false,
        tilesLeft: [],
      });

      onSuccess();
      onClose();
    } catch (err: any) {
      error = err.message || '방 참가에 실패했습니다';
    } finally {
      isLoading = false;
    }
  };

  const handleBackdropClick = (e: MouseEvent) => {
    if (e.target === e.currentTarget) {
      onClose();
    }
  };
</script>

{#if isOpen && room}
  <!-- svelte-ignore a11y-click-events-have-key-events -->
  <!-- svelte-ignore a11y-no-noninteractive-element-interactions -->
  <div class={s.modal} on:click={handleBackdropClick} role="dialog" aria-modal="true">
    <!-- svelte-ignore a11y-click-events-have-key-events -->
    <!-- svelte-ignore a11y-no-noninteractive-element-interactions -->
    <div class={s['modal__content']} on:click={(e) => e.stopPropagation()} role="document">
      <h2 class={s['modal__title']}>방 참가</h2>
      <div class={s['join-room-info']}>
        <div class={s['join-room-info__title']}>방 제목 : {room.title}</div>
        <div class={s['join-room-info__meta']}>
          <span class={s['join-room-info__label']}>승부 수 : </span>
          <span class={s['join-room-info__format']}>{FORMAT_LABELS[room.format]}</span>
          {#if room.overtime}
            <span class={s['join-room-info__overtime']}>연장</span>
          {/if}
        </div>
      </div>

      <form class={s['modal__form']} on:submit={handleSubmit}>
        <div class={s['form__group']}>
          <label for="nickname" class={s['form__label']}>닉네임</label>
          <input
            id="nickname"
            type="text"
            class={s['form__input']}
            bind:value={formData.nickname}
            placeholder="닉네임을 입력하세요"
            maxlength="20"
            disabled={isLoading}
          />
        </div>

        {#if room.locked}
          <div class={s['form__group']}>
            <label for="password" class={s['form__label']}>비밀번호</label>
            <input
              id="password"
              type="password"
              class={s['form__input']}
              bind:value={formData.password}
              placeholder="비밀번호를 입력하세요"
              maxlength="20"
              disabled={isLoading}
            />
          </div>
        {/if}

        {#if error}
          <div class={s['form__error']}>{error}</div>
        {/if}

        <div class={s['modal__actions']}>
          <button
            type="button"
            class={s['modal__cancel']}
            on:click={onClose}
            disabled={isLoading}
          >
            취소
          </button>
          <button
            type="submit"
            class={s['modal__submit']}
            disabled={isLoading}
          >
            {isLoading ? '참가 중...' : '참가하기'}
          </button>
        </div>
      </form>
    </div>
  </div>
{/if}

// apps/frontend/src/features/room-join/RoomJoinModal.tsx
import { useState } from 'react';
import { api } from '@/shared/api/endpoints';
import { useRoomStore } from '@/entities/room/store';
import { usePlayerStore } from '@/entities/player/store';
import { RoomInfo } from '@shared/types/room';
import { FORMAT_LABELS } from '@shared/constants/index';
import s from './RoomJoinModal.module.scss';

type Props = {
  room: RoomInfo | null;
  isOpen: boolean;
  onClose: () => void;
  onSuccess: () => void;
};

export const RoomJoinModal: React.FC<Props> = ({ room, isOpen, onClose, onSuccess }) => {
  const { setRoom } = useRoomStore();
  const { setMe } = usePlayerStore();
  const [formData, setFormData] = useState({ nickname: '', password: '' });
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string>('');

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!room) return;

    setError('');

    if (!formData.nickname.trim()) {
      setError('닉네임을 입력해주세요');
      return;
    }

    if (room.locked && !formData.password) {
      setError('비밀번호를 입력해주세요');
      return;
    }

    setIsLoading(true);
    try {
      const response = await api.joinRoom({
        roomId: room.id,
        nickname: formData.nickname,
        password: formData.password || undefined,
      });

      setRoom({
        id: room.id,
        title: room.title,
        locked: room.locked,
        format: room.format,
        overtime: room.overtime,
        playerCount: room.playerCount,
      });

      setMe({
        id: response.playerId,
        nickname: formData.nickname,
        ready: false,
        tilesLeft: [],
      });

      onSuccess();
      onClose();
    } catch (err: any) {
      setError(err.message || '방 참가에 실패했습니다');
    } finally {
      setIsLoading(false);
    }
  };

  if (!isOpen || !room) return null;

  return (
    <div className={s.modal} onClick={onClose}>
      <div className={s['modal__content']} onClick={(e) => e.stopPropagation()}>
        <h2 className={s['modal__title']}>방 참가</h2>
        <div className={s['join-room-info']}>
          <div className={s['join-room-info__title']}>방 제목 : {room.title}</div>
          <div className={s['join-room-info__meta']}>
            <span className={s['join-room-info__label']}>승부 수 : </span>
            <span className={s['join-room-info__format']}>{FORMAT_LABELS[room.format]}</span>
            {room.overtime && <span className={s['join-room-info__overtime']}>연장</span>}
          </div>
        </div>

        <form className={s['modal__form']} onSubmit={handleSubmit}>
          <div className={s['form__group']}>
            <label className={s['form__label']}>닉네임</label>
            <input
              type="text"
              className={s['form__input']}
              value={formData.nickname}
              onChange={(e) => setFormData({ ...formData, nickname: e.target.value })}
              placeholder="닉네임을 입력하세요"
              maxLength={20}
              disabled={isLoading}
              autoFocus
            />
          </div>

          {room.locked && (
            <div className={s['form__group']}>
              <label className={s['form__label']}>비밀번호</label>
              <input
                type="password"
                className={s['form__input']}
                value={formData.password}
                onChange={(e) => setFormData({ ...formData, password: e.target.value })}
                placeholder="비밀번호를 입력하세요"
                maxLength={20}
                disabled={isLoading}
              />
            </div>
          )}

          {error && <div className={s['form__error']}>{error}</div>}

          <div className={s['modal__actions']}>
            <button
              type="button"
              className={s['modal__cancel']}
              onClick={onClose}
              disabled={isLoading}
            >
              취소
            </button>
            <button
              type="submit"
              className={s['modal__submit']}
              disabled={isLoading}
            >
              {isLoading ? '참가 중...' : '참가하기'}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};
